package yh326.typecheck;

import yh326.ast.node.*;
import yh326.lex.XiSymbol;
import yh326.gen.lexer;
import yh326.gen.parser;
import yh326.gen.sym;
import yh326.ast.exception.*;
/*top class for implementing typechecker*/
public class typechecker {
    // construct the AST from the parser
    public typechecker(parser p) {
        // not implemented
    }    

    /*
      Invoke type check on the root of the ast
    */
    public void typecheck() throws TypeErrorException {
       /* not implemented
       try {
            root.typeCheck()       
        } catch(Exception e) {
            throw new RuntimeExcepteion("NodeType error");
        }*/
    }
    //private:
        Node root;  // root node for the AST generated by parser
}
