package yh326_a1;

public interface sym {
	public static final int EOF = 0;
        public static final int USE = 1;
        public static final int IF = 2;
        public static final int WHILE = 3;
        public static final int ELSE = 4;
        public static final int RETURN = 5;
        public static final int IDENTIFIER = 6;
        public static final int INT = 7;
        public static final int INTEGER = 8;
        public static final int BOOL = 9;
        public static final int BOOLEAN = 10;
//        public static final int SEPARATOR = 11;
//        public static final int OPERATOR = 12;
        public static final int STRING = 13;
        public static final int LENGTH = 14;
        public static final int UNDERSCORE = 15;
        public static final int ERROR = 16;
        public static final int CHARACTER = 17;
        public static final int OPEN_BRACKET = 18;
        public static final int CLOSE_BRACKET = 19;
        public static final int OPEN_PAREN = 20;
        public static final int CLOSE_PAREN = 20;
        public static final int OPEN_BRACE = 22;
        public static final int CLOSE_BRACE = 23;
        public static final int COMMA = 24;
        public static final int SEMICOLON = 25;
        public static final int COLON = 26;
        public static final int ASSIGN = 27;
        public static final int MINUS = 28;
        public static final int BOOLEAN_NEGATION = 29;
        public static final int MULTIPLICATION = 30;
        public static final int HIGH_MULTI = 31;
        public static final int DIVISION = 32;
        public static final int REMAINER = 33;
        public static final int ADDITION = 34;
        public static final int SUBTRACTION = 35;
        public static final int LT = 36;
        public static final int LEQ = 37;
        public static final int GEQ = 38;
        public static final int GT = 39;
        public static final int EQUAL = 40;
        public static final int NOT_EQUAL = 41;
        public static final int LOGICAL_AND = 42;
        public static final int LOGICAL_OR = 43;
    }
