#!/bin/bash
rm -rf bin/
rm -rf src/bsa52_ml2558_yz2369_yh326/gen/
rm -rf __pycache__/
rm -rf xi_executable
rm -rf temp/
find . -type f -name '*.lexed' -delete
find . -type f -name '*.parsed' -delete
find . -type f -name '*.typed' -delete
find . -type f -name '*.ir' -delete
find . -type f -name '*.ir.nml' -delete
find . -type f -name '*.s' -delete
find . -type f -name '*.s.nml' -delete
find . -type f -name '*.dot' -delete
