#!/bin/bash

rm -rf temp
mkdir temp
if [ $1 == "a3" ] || [ $1 == "a4" ] || [ $1 == "a5" ]; then
    pkg=$1
    mkdir temp/xi
    cp tests/$pkg/testcases/* temp/xi
    cp tests/$pkg/answers/* temp/xi
    xth -compilerpath . -testpath temp/xi -workpath temp tests/$pkg/xthScript
elif [ $1 == "f2" ] || [ $1 == "f3" ] || [ $1 == "f4" ] || [ $1 == "f5" ]; then
    an=$(echo $1 | cut -c2-2)
    pkg=failedcases_a$an
    xth -compilerpath . -testpath tests/$pkg -workpath temp tests/$pkg/xthScript
else
    pa=pa$1
    xth -compilerpath . -testpath ~/xth/tests/$pa/ -workpath ./temp/ ~/xth/tests/$pa/xthScript
fi
