#!/bin/bash

rm -rf temp
mkdir temp
if [ $1 == "a3" ] || [ $1 == "a4" ] || [ $1 == "a5" ]; then
    pkg=yh326_$1
    mkdir temp/xi
    cp tests/$pkg/testcases/* temp/xi
    cp tests/$pkg/answers/* temp/xi
    xth -compilerpath . -testpath temp/xi -workpath temp tests/$pkg/xthScript
elif [ $1 == "f4" ]; then
    pkg=failedcases_a4
    mkdir temp/xi
    xth -compilerpath . -testpath tests/$pkg -workpath temp tests/$pkg/xthScript
else
    pa=pa$1
    xth -compilerpath . -testpath ~/xth/tests/$pa/ -workpath ./temp/ ~/xth/tests/$pa/xthScript
fi
