#!/bin/bash
dir=`cd $(dirname "$0"); pwd`
a1=yh326_a1

# a1 - .flex -> Lexer
rm -rf $dir/src/$a1/XiLexer.java*
jflex $dir/src/$a1/XiLexer.flex
sed -i "1s/^/package $a1;\n\n/" $dir/src/$a1/XiLexer.java

# a1 - Compile lexer
javac -cp $dir/lib/java_cup.jar:$dir/src/ -d $dir/bin/ $dir/src/$a1/LexerWrapper.java

# a2 -
# $dir/lib/cup $dir/src/$a2/XiParser.cup
