#!/bin/bash
dir=`cd $(dirname "$0"); pwd`
pkg=yh326
cp=$dir/lib/java_cup.jar:$dir/lib/src/:$dir/src/

rm -rf $dir/src/$pkg/lexer.java*
jflex $dir/src/$pkg/xi.flex
sed -i "1s/^/package $pkg;\n\n/" $dir/src/$pkg/lexer.java

$dir/lib/cup -interface -destdir $dir/src/$pkg/ $dir/src/$pkg/xi.cup
javac -cp $cp -d $dir/bin/ $dir/src/$pkg/Main.java
