
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package yh326;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int UNDERSCORE = 39;
  public static final int SUBTRACTION = 30;
  public static final int LENGTH = 8;
  public static final int LT = 31;
  public static final int CLOSE_BRACKET = 14;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int INTEGER_NEGATION = 23;
  public static final int INT = 9;
  public static final int DIVISION = 27;
  public static final int RETURN = 7;
  public static final int BOOLEAN_NEGATION = 24;
  public static final int OPEN_BRACE = 17;
  public static final int CLOSE_BRACE = 18;
  public static final int SEMICOLON = 20;
  public static final int ELSE = 6;
  public static final int ERROR = 40;
  public static final int CHARACTER = 42;
  public static final int IDENTIFIER = 2;
  public static final int HIGH_MULTI = 26;
  public static final int EOF = 0;
  public static final int IF = 4;
  public static final int INTEGER = 12;
  public static final int COMMA = 19;
  public static final int MULTIPLICATION = 25;
  public static final int USE = 3;
  public static final int EQUAL = 35;
  public static final int LOGICAL_AND = 37;
  public static final int OPEN_BRACKET = 13;
  public static final int COLON = 21;
  public static final int LOGICAL_OR = 38;
  public static final int GT = 34;
  public static final int BOOLEAN = 11;
  public static final int GEQ = 33;
  public static final int OPEN_PAREN = 15;
  public static final int BOOL = 10;
  public static final int REMAINDER = 28;
  public static final int ADDITION = 29;
  public static final int NOT_EQUAL = 36;
  public static final int LEQ = 32;
  public static final int STRING = 41;
  public static final int WHILE = 5;
  public static final int CLOSE_PAREN = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "USE",
  "IF",
  "WHILE",
  "ELSE",
  "RETURN",
  "LENGTH",
  "INT",
  "BOOL",
  "BOOLEAN",
  "INTEGER",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "ASSIGN",
  "INTEGER_NEGATION",
  "BOOLEAN_NEGATION",
  "MULTIPLICATION",
  "HIGH_MULTI",
  "DIVISION",
  "REMAINDER",
  "ADDITION",
  "SUBTRACTION",
  "LT",
  "LEQ",
  "GEQ",
  "GT",
  "EQUAL",
  "NOT_EQUAL",
  "LOGICAL_AND",
  "LOGICAL_OR",
  "UNDERSCORE",
  "ERROR",
  "STRING",
  "CHARACTER"
  };
}

