package yh326;

/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/vagrant/shared/pa/src/yh326/XiLexer.flex</tt>
 */
public class XiLexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int YYSTRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\60\1\61\1\1\22\0\1\3\1\37\1\55"+
    "\2\0\1\36\1\42\1\10\1\46\1\47\1\34\1\32\1\53\1\33"+
    "\1\0\1\12\1\11\11\5\1\52\1\54\1\40\1\41\1\35\2\0"+
    "\6\6\24\4\1\44\1\56\1\45\1\0\1\7\1\0\1\20\1\25"+
    "\2\6\1\16\1\17\1\31\1\30\1\23\2\4\1\21\1\4\1\24"+
    "\1\26\2\4\1\14\1\22\1\13\1\15\1\4\1\27\1\57\2\4"+
    "\1\50\1\43\1\51\7\0\1\60\u1fa2\0\1\60\1\60\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\4"+
    "\1\7\11\3\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\2\35"+
    "\1\36\1\34\1\1\2\37\1\40\1\1\1\2\6\3"+
    "\1\41\3\3\1\0\1\42\1\43\1\44\1\45\1\34"+
    "\1\0\1\46\1\0\1\46\1\0\1\2\2\3\1\47"+
    "\3\3\1\50\2\3\1\51\1\52\1\53\1\0\1\54"+
    "\1\3\1\55\2\3\1\56\1\3\1\52\1\0\1\57"+
    "\1\3\1\60\1\3\1\61\1\52\1\0\1\62\1\63"+
    "\1\52\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\226\0\310\0\372\0\226"+
    "\0\226\0\226\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\226\0\226\0\u0320\0\u0352"+
    "\0\226\0\u0384\0\u03b6\0\u03e8\0\226\0\226\0\226\0\226"+
    "\0\226\0\226\0\226\0\226\0\226\0\226\0\226\0\226"+
    "\0\226\0\u041a\0\226\0\226\0\u044c\0\u047e\0\u04b0\0\226"+
    "\0\u047e\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e"+
    "\0\u0640\0\310\0\u0672\0\u06a4\0\u06d6\0\u0708\0\226\0\226"+
    "\0\226\0\226\0\u073a\0\u076c\0\226\0\u047e\0\u079e\0\u07d0"+
    "\0\u0802\0\u0834\0\u0866\0\310\0\u0898\0\u08ca\0\u08fc\0\310"+
    "\0\u092e\0\u0960\0\226\0\u0992\0\226\0\u09c4\0\310\0\u09f6"+
    "\0\310\0\u0a28\0\u0a5a\0\310\0\u0a8c\0\u0abe\0\u0af0\0\226"+
    "\0\u0b22\0\310\0\u0b54\0\310\0\u0b86\0\u0bb8\0\310\0\310"+
    "\0\226\0\u0bea";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\3\5\1\6\1\7\1\6\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\6\1\21"+
    "\1\6\1\22\1\6\1\23\1\6\1\24\2\6\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\4\1\6\1\4\1\5\1\51"+
    "\1\52\1\53\52\51\1\54\1\55\1\51\2\4\1\56"+
    "\1\57\1\60\5\56\1\61\45\56\1\62\1\56\2\4"+
    "\66\0\6\6\1\0\17\6\25\0\1\6\7\0\1\7"+
    "\3\0\1\7\62\0\1\63\53\0\6\6\1\0\1\6"+
    "\1\64\15\6\25\0\1\6\6\0\6\6\1\0\3\6"+
    "\1\65\13\6\25\0\1\6\6\0\6\6\1\0\7\6"+
    "\1\66\7\6\25\0\1\6\6\0\6\6\1\0\6\6"+
    "\1\67\10\6\25\0\1\6\6\0\6\6\1\0\5\6"+
    "\1\70\11\6\25\0\1\6\6\0\6\6\1\0\3\6"+
    "\1\71\13\6\25\0\1\6\6\0\6\6\1\0\4\6"+
    "\1\72\4\6\1\73\5\6\25\0\1\6\6\0\6\6"+
    "\1\0\13\6\1\74\3\6\25\0\1\6\6\0\6\6"+
    "\1\0\15\6\1\75\1\6\25\0\1\6\37\0\1\76"+
    "\65\0\1\77\61\0\1\100\61\0\1\101\61\0\1\102"+
    "\22\0\1\53\57\0\1\51\2\0\54\51\1\103\2\0"+
    "\10\104\1\105\51\104\2\0\1\60\57\0\1\106\2\104"+
    "\5\106\1\107\46\106\1\110\2\104\1\63\1\111\1\5"+
    "\57\63\4\0\6\6\1\0\2\6\1\112\14\6\25\0"+
    "\1\6\6\0\6\6\1\0\1\113\16\6\25\0\1\6"+
    "\6\0\6\6\1\0\3\6\1\114\13\6\25\0\1\6"+
    "\6\0\6\6\1\0\7\6\1\115\7\6\25\0\1\6"+
    "\6\0\6\6\1\0\6\6\1\116\10\6\25\0\1\6"+
    "\6\0\6\6\1\0\11\6\1\117\5\6\25\0\1\6"+
    "\6\0\6\6\1\0\1\120\16\6\25\0\1\6\6\0"+
    "\6\6\1\0\13\6\1\121\3\6\25\0\1\6\6\0"+
    "\6\6\1\0\10\6\1\122\6\6\25\0\1\6\37\0"+
    "\1\123\31\0\2\124\2\0\1\124\4\0\3\124\4\0"+
    "\1\124\34\0\10\104\1\125\51\104\10\0\1\105\51\0"+
    "\5\104\2\126\1\104\1\105\1\126\4\104\3\126\4\104"+
    "\1\126\34\104\2\0\1\5\63\0\6\6\1\0\3\6"+
    "\1\127\13\6\25\0\1\6\6\0\6\6\1\0\2\6"+
    "\1\130\14\6\25\0\1\6\6\0\6\6\1\0\3\6"+
    "\1\131\13\6\25\0\1\6\6\0\6\6\1\0\7\6"+
    "\1\132\7\6\25\0\1\6\6\0\6\6\1\0\16\6"+
    "\1\133\25\0\1\6\6\0\6\6\1\0\6\6\1\134"+
    "\10\6\25\0\1\6\6\0\6\6\1\0\6\6\1\135"+
    "\10\6\25\0\1\6\7\0\2\136\2\0\1\136\4\0"+
    "\3\136\4\0\1\136\34\0\5\104\2\137\1\104\1\140"+
    "\1\137\4\104\3\137\4\104\1\137\34\104\4\0\6\6"+
    "\1\0\1\6\1\141\15\6\25\0\1\6\6\0\6\6"+
    "\1\0\3\6\1\142\13\6\25\0\1\6\6\0\6\6"+
    "\1\0\1\143\16\6\25\0\1\6\6\0\6\6\1\0"+
    "\3\6\1\144\13\6\25\0\1\6\7\0\2\145\2\0"+
    "\1\145\4\0\3\145\4\0\1\145\34\0\5\104\2\146"+
    "\1\104\1\140\1\146\4\104\3\146\4\104\1\146\34\104"+
    "\4\0\6\6\1\0\11\6\1\147\5\6\25\0\1\6"+
    "\6\0\6\6\1\0\15\6\1\150\1\6\25\0\1\6"+
    "\7\0\2\151\2\0\1\151\4\0\3\151\4\0\1\151"+
    "\34\0\5\104\2\152\1\104\1\140\1\152\4\104\3\152"+
    "\4\104\1\152\44\104\1\140\51\104";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3100];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\3\11\12\1\2\11\2\1\1\11"+
    "\3\1\15\11\1\1\2\11\3\1\1\11\15\1\1\0"+
    "\4\11\1\1\1\0\1\11\1\0\1\1\1\0\12\1"+
    "\1\11\1\1\1\11\1\0\10\1\1\0\1\11\5\1"+
    "\1\0\2\1\1\11\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuilder string = new StringBuilder();
    int column = 0;

    private Symbol symbol(int type, Object value) {
        return new XiSymbol(type, null, value, yyline+1, yycolumn+1);
    }

    private Symbol symbol(int type, String typeString, Object value) {
        return new XiSymbol(type, typeString, value, yyline+1, yycolumn+1);
    }

    private Symbol symbol(int type, Object value, int line, int column) {
        return new XiSymbol(type, null, value, line+1, column+1);
    }

    private Symbol symbol(int type, String typeString, Object value, int line, int column) {
        return new XiSymbol(type, typeString, value, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public XiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF, yytext());
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(ERROR, "error: unrecognized character: "+yytext());
            }
          case 52: break;
          case 2: 
            { /* ignore */
            }
          case 53: break;
          case 3: 
            { return symbol(IDENTIFIER,      "id",      yytext());
            }
          case 54: break;
          case 4: 
            { return symbol(INTEGER_LITERAL, "integer", yytext());
            }
          case 55: break;
          case 5: 
            { return symbol(UNDERSCORE,    yytext());
            }
          case 56: break;
          case 6: 
            { yybegin(CHARLITERAL); column = yycolumn;
            }
          case 57: break;
          case 7: 
            { return symbol(DIVIDE,        yytext());
            }
          case 58: break;
          case 8: 
            { return symbol(PLUS,          yytext());
            }
          case 59: break;
          case 9: 
            { return symbol(MINUS,         yytext());
            }
          case 60: break;
          case 10: 
            { return symbol(TIMES,         yytext());
            }
          case 61: break;
          case 11: 
            { return symbol(GT,            yytext());
            }
          case 62: break;
          case 12: 
            { return symbol(MODULO,        yytext());
            }
          case 63: break;
          case 13: 
            { return symbol(NOT,           yytext());
            }
          case 64: break;
          case 14: 
            { return symbol(LT,            yytext());
            }
          case 65: break;
          case 15: 
            { return symbol(GETS,          yytext());
            }
          case 66: break;
          case 16: 
            { return symbol(AND,           yytext());
            }
          case 67: break;
          case 17: 
            { return symbol(OR,            yytext());
            }
          case 68: break;
          case 18: 
            { return symbol(OPEN_BRACKET,  yytext());
            }
          case 69: break;
          case 19: 
            { return symbol(CLOSE_BRACKET, yytext());
            }
          case 70: break;
          case 20: 
            { return symbol(OPEN_PAREN,    yytext());
            }
          case 71: break;
          case 21: 
            { return symbol(CLOSE_PAREN,   yytext());
            }
          case 72: break;
          case 22: 
            { return symbol(OPEN_BRACE,    yytext());
            }
          case 73: break;
          case 23: 
            { return symbol(CLOSE_BRACE,   yytext());
            }
          case 74: break;
          case 24: 
            { return symbol(COLON,         yytext());
            }
          case 75: break;
          case 25: 
            { return symbol(COMMA,         yytext());
            }
          case 76: break;
          case 26: 
            { return symbol(SEMICOLON,     yytext());
            }
          case 77: break;
          case 27: 
            { yybegin(YYSTRING); column = yycolumn; string.setLength(0);
            }
          case 78: break;
          case 28: 
            { string.append(yytext());
            }
          case 79: break;
          case 29: 
            { yybegin(YYINITIAL); return symbol(ERROR, ": Unterminated string at end of line", yyline, column);
            }
          case 80: break;
          case 30: 
            { yybegin(YYINITIAL); return symbol(STRING_LITERAL, "string", "" + string, yyline, column);
            }
          case 81: break;
          case 31: 
            { yybegin(YYINITIAL); return symbol(ERROR, "error: unterminated character literal at end of line", yyline, column);
            }
          case 82: break;
          case 32: 
            { yybegin(YYINITIAL); return symbol(ERROR, "error: empty character literal", yyline, column);
            }
          case 83: break;
          case 33: 
            { return symbol(IF,            yytext());
            }
          case 84: break;
          case 34: 
            { return symbol(GEQ,           yytext());
            }
          case 85: break;
          case 35: 
            { return symbol(NOT_EQUAL,     yytext());
            }
          case 86: break;
          case 36: 
            { return symbol(LEQ,           yytext());
            }
          case 87: break;
          case 37: 
            { return symbol(EQUAL,         yytext());
            }
          case 88: break;
          case 38: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, "character", yytext().substring(0, yylength()-1), yyline, column);
            }
          case 89: break;
          case 39: 
            { return symbol(USE,           yytext());
            }
          case 90: break;
          case 40: 
            { return symbol(INT,           yytext());
            }
          case 91: break;
          case 41: 
            { return symbol(TIMES_SHIFT,   yytext());
            }
          case 92: break;
          case 42: 
            { string.append((char) Integer.parseInt(yytext().substring(2), 16));
            }
          case 93: break;
          case 43: 
            { yybegin(YYINITIAL); return symbol(ERROR, "error: invalid character literal: \'" + yytext(), yyline, column);
            }
          case 94: break;
          case 44: 
            { return symbol(TRUE,          yytext());
            }
          case 95: break;
          case 45: 
            { return symbol(ELSE,          yytext());
            }
          case 96: break;
          case 46: 
            { return symbol(BOOL,          yytext());
            }
          case 97: break;
          case 47: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, "character", "" + Integer.parseInt(yytext().substring(2, yylength()-1), 16), yyline, column);
            }
          case 98: break;
          case 48: 
            { return symbol(FALSE,         yytext());
            }
          case 99: break;
          case 49: 
            { return symbol(WHILE,         yytext());
            }
          case 100: break;
          case 50: 
            { return symbol(RETURN,        yytext());
            }
          case 101: break;
          case 51: 
            { return symbol(LENGTH,        yytext());
            }
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java XiLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        XiLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new XiLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
