#!/bin/bash
DIR=`cd $(dirname "$0"); pwd`
BINDIR=$DIR/gen/yh326_a1
if [ -f $DIR/gen/yh326_a1/XiLexer.java ]; then
    rm $DIR/gen/yh326_a1/XiLexer.java
fi
jflex -d $BINDIR $DIR/yh326_a1/XiLexer.flex
sed -i '1s/^/package yh326_a1;\n\n/' $BINDIR/XiLexer.java
cp $DIR/yh326_a1/LexerWrapper.java $BINDIR
javac -cp $DIR/gen/ -d $DIR/gen/ $BINDIR/LexerWrapper.java
